table 'VSCode Usage (Stack Overflow De'
	lineageTag: ba529fea-bea4-4286-9168-f2a7fc3a1311

	column Year
		dataType: string
		lineageTag: 93d03d27-5b0c-4f5f-a5d5-405e5d02b075
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Usage
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9552e3f3-a28e-4f38-a7bd-a39313658a91
		summarizeBy: sum
		sourceColumn: Usage

		annotation SummarizationSetBy = Automatic

	column 'Year Date' = DATE( VALUE('VSCode Usage (Stack Overflow De'[Year]), 1, 1 )
		formatString: General Date
		lineageTag: d6359205-12bd-4f36-889c-d0e9e78ec9fc
		summarizeBy: none

		variation Variation
			isDefault
			relationship: a25788fe-4cbd-4fd7-bf14-735bfaf7a8b5
			defaultHierarchy: LocalDateTable_46f00ca7-7b51-4cb8-bb5f-f76ed3fcdbb9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'VSCode Usage (Stack Overflow De' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Simon\Desktop\JUST IT\VSCode PR Analysis Additional Data.xlsx"), null, true),
				    #"VSCode Usage (Stack Overflow De_Sheet" = Source{[Item="VSCode Usage (Stack Overflow De",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"VSCode Usage (Stack Overflow De_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Usage", Percentage.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

